### ISSUE TITLE
don't validate properties.attributes

### ISSUE THREAD

**Issue by neonstalwart** [alexmingoia/virtual-dom-stringify#17]
what do you think about rendering everything in `properties.attributes` regardless of whether or not it's known to be valid?

```js
stringify(h('meta', { 
    attributes: {
        property: 'foo',
        content: 'bar'
    }
}));
```

the idea is that if i put something in `attributes`, i don't want you to care if it's valid or not - i really do mean i want an attribute with that exact name.

if you want this, i can work on a PR for it.

**Comment by alexmingoia** [comment]
I agree. It shouldn't be the serializer's responsibility to validate attributes. Including it in this module is kind of leaky... PR welcome otherwise I'll get to it tomorrow.
