### ISSUE TITLE
Does not handle widgets

### ISSUE THREAD

**Issue by alexmingoia** [alexmingoia/virtual-dom-stringify#18]

**Comment by refractalize** [comment]
Hi @alexmingoia what was the outcome of this? We'd be interested in making a pull request for this, any reason it would be rejected?

**Comment by alexmingoia** [comment]
I may have closed this accidentally. What is the issue with widgets you're having? Widgets somewhat by definition cannot be stringified or serialized - at least not in a standard way.

**Comment by refractalize** [comment]
Yeah, good point about them not being serializable. I suppose I'm using widgets are serializable, in theory at least, in that they generate virtual DOM, not DOM. Will think about this a bit harder :)
