### ISSUE TITLE
Script text is encoded with virtual-dom ^ 1.3.0

### ISSUE THREAD

**Issue by matthewp** [alexmingoia/virtual-dom-stringify#19]
Because of this commit: https://github.com/Matt-Esch/virtual-dom/commit/e21dc39f1677382bd4a5a651a96ca9ebd51c5646

tagNames are now capitalized by default. Because of this a script's text node will be encoded.  I'll submit a PR to fix.

**Comment by matthewp** [comment]
This test is passing: https://github.com/alexmingoia/virtual-dom-stringify/blob/master/test/stringify.js#L102

The reason is that the capitalization only happens when using virtual-hyperscript. Is it ok if I change this test to use `h` or would you prefer I create a new test?

**Comment by matthewp** [comment]
Went ahead and submitted a PR, can resubmit if you'd prefer there be separate tests but I don't think it matters, this new test should cover both.

**Comment by alexmingoia** [comment]
Thanks :+1:
