### ISSUE TITLE
Shouldn't encode UTF-8 entities

### ISSUE THREAD

**Issue by bitinn** [alexmingoia/virtual-dom-stringify#21]
I assume this line is done for security reason?

https://github.com/alexmingoia/virtual-dom-stringify/blob/master/lib/stringify.js#L116

but I do think `he.encode` isn't meant for security, you would be better of just using `escape-html` module that handles `&, <, >, ', "` only.

Otherwise we are just encoding UTF-8 entities unnecessarily, in my cases, all the Chinese on page :)

cc @mathiasbynens

**Comment by mathiasbynens** [comment]
You’d need to escape `` ` `` as well.

**Comment by mathiasbynens** [comment]
You’re right that HTML-encoding non-ASCII symbols doesn’t necessarily improve security, but there are some benefits to having the output be full ASCII: it avoids all kinds of encoding issues.

**Comment by bitinn** [comment]
@mathiasbynens Whether backtick is a source of XSS are case-dependent right? In this case we are specifically talking about text content within a valid tag, not attributes or scripts (this module does not encode inline `<script>` at all, since it's a dom builder).

I do think UTF-8 is preferable if your website content involves CJK, you can search source much easier, and copy-paste always result in decoded UTF-8, not entities.

**Comment by mathiasbynens** [comment]
@bitinn Whether _anything_ is a source of XSS is context-dependent. I wasn’t thinking of inline `<script>` though: <https://github.com/mathiasbynens/he/blob/089b8afba8b3efe865e1c5bc38ed063103ff8a05/he.js#L45-L49>.

> I do think UTF-8 is preferable if your website content involves CJK, you can search source much easier, and copy-paste always result in decoded UTF-8, not entities.

You mean Unicode, not UTF-8. Anyhow, it looks like you’d like to see an `asciiSafe` option that would toggle between `he.encode` and `he.escape`.

**Comment by bitinn** [comment]
@mathiasbynens Great, at least I am looking at the same source (html5sec) for backtick xss as you do; I don't think those 3 examples are a problem in this specific case.

As for options, yeah, `asciiSafe` that would be good, similar to `cheerio`'s `decodeEntities` flag.

PS: I honestly haven't seen a single site in Far East regions (eg. China/Japan/Taiwan) using ASCII instead of Unicode (I meant they all use decoded Unicode, not encoded).

**Comment by alexmingoia** [comment]
Thanks for your help guys :+1: Added `options.asciiSafe` to toggle between encoding non-ASCII symbols.

**Comment by bitinn** [comment]
@alexmingoia thx for the prompt fix :)

**Comment by mathiasbynens** [comment]
:+1:
