### ISSUE TITLE
Support svg attributes in a different namespace

### ISSUE THREAD

**Issue by bitinn** [alexmingoia/virtual-dom-stringify#24]
`virtual-dom` use attribute hooks to handle those values. We need to check `isHook(value)` in the node.properties loop, in order to render this properly.

```
    var node = svg('use', {
      'xlink:href': '/icons.svg#icon-name'
    });
    assert.equal(stringify(node), '<use xlink:href="/icons.svg#icon-name"></use>');
```

This pattern is common when using SVG icon system.

Also note that virtual-dom is now at 2.0 :)

**Comment by alexmingoia** [comment]
PR welcome... don't have much time to look at this

**Comment by bitinn** [comment]
Thx! sorry i couldn't get this repo setup on iojs, probably due to node-gyp issues with iojs.

Though I think there are better ways to check for attribute hooks (used for these namespaced attributes), see what we did here: https://github.com/nthtran/vdom-to-html/blob/master/index.js#L55
